/* Generated by the Nim Compiler v1.6.10 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var objectID_687866018 = [0];
var cnv_469762050 = document.getElementById("c1");
var ctx_469762051 = cnv_469762050.getContext('2d');
ctx_469762051.beginPath();
ctx_469762051.fillStyle = 'rgb(10, 230, 80)';
ctx_469762051.rect(10, 10, 60, 40);
ctx_469762051.fill();
